spring.application.name=nexora-ai
spring.datasource.url=jdbc:postgresql://localhost:5432/nexora_ai
spring.datasource.username=francismarshall
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true