/*
 * Workload 5 - Protected Market Data Authorization
 *
 * Adds durable governance support for:
 *
 * 1. Registered tuning periods used for validation warm-up.
 * 2. Separate explicit holdout authorization records.
 *
 * ProtectedRunGuardRepository continues to manage the
 * RESERVED -> RUNNING_UNEXPOSED -> EXPOSED -> SPENT lifecycle.
 */


/*
 * ============================================================
 * REGISTERED TUNING PERIOD
 * ============================================================
 */

CREATE TABLE protected_tuning_period (

                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                         strategy_version TEXT NOT NULL,

                                         tuning_period_id TEXT NOT NULL,

                                         period_start DATE NOT NULL,

                                         period_end DATE NOT NULL,

                                         created_at TIMESTAMPTZ NOT NULL
                                             DEFAULT CURRENT_TIMESTAMP,

                                         CONSTRAINT ck_protected_tuning_period_dates
                                             CHECK (period_start <= period_end),

                                         CONSTRAINT uq_protected_tuning_period_strategy
                                             UNIQUE (strategy_version),

                                         CONSTRAINT uq_protected_tuning_period_identity
                                             UNIQUE (
                                                     strategy_version,
                                                     tuning_period_id
                                                 )
);


/*
 * Supports date-range lookups.
 */

CREATE INDEX idx_protected_tuning_period_dates
    ON protected_tuning_period (
                                period_start,
                                period_end
        );


/*
 * ============================================================
 * EXPLICIT HOLDOUT AUTHORIZATION
 * ============================================================
 *
 * Reserving or acquiring a protected holdout target does
 * not automatically authorize access to holdout market data.
 *
 * Holdout authorization must exist as a separate durable
 * PostgreSQL record.
 */

CREATE TABLE protected_holdout_authorization (

                                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                                 guard_id BIGINT NOT NULL,

                                                 strategy_version TEXT NOT NULL,

                                                 protected_period_id TEXT NOT NULL,

                                                 authorization_timestamp TIMESTAMPTZ NOT NULL,

                                                 created_at TIMESTAMPTZ NOT NULL
                                                     DEFAULT CURRENT_TIMESTAMP,

                                                 CONSTRAINT fk_protected_holdout_authorization_guard
                                                     FOREIGN KEY (guard_id)
                                                         REFERENCES protected_run_guard (id)
                                                         ON DELETE RESTRICT,

                                                 CONSTRAINT uq_protected_holdout_authorization_guard
                                                     UNIQUE (guard_id),

                                                 CONSTRAINT uq_protected_holdout_authorization_target
                                                     UNIQUE (
                                                             strategy_version,
                                                             protected_period_id
                                                         )
);


/*
 * Supports authorization lookups by strategy and period.
 */

CREATE INDEX idx_protected_holdout_authorization_target
    ON protected_holdout_authorization (
                                        strategy_version,
                                        protected_period_id
        );